### ISSUE TITLE
After Compiling Source Getting Following Error While creating Build sing Module.

### ISSUE THREAD

**Issue by sachinkumarsharma** [arskinner/Appcelerator-CardIO#11]
Hi ,

I have compiled Given Module , by Just Disabling CVV Number. I am trying to Compile the Titanium Project using this New Module , But getting Following Error.

[ERROR] :  The following build commands failed:
[ERROR] :   Ld build/Intermediates/Test.build/Debug-iphoneos/Test.build/Objects-normal/armv7/Test normal armv7
[ERROR] :   Ld build/Intermediates/Test.build/Debug-iphoneos/Test.build/Objects-normal/arm64/Test normal arm64
[ERROR] :  (2 failures)

Please suggest.

**Comment by arskinner** [comment]
You might give this a go with the latest code, using the new `appc ti build` command
