### ISSUE TITLE
Is there any new release for Titanium SDK 6.0.0.GA?

### ISSUE THREAD

**Issue by junweimah** [arskinner/Appcelerator-CardIO#12]
I am planning to upgrade to 6.0.0.GA but this module is not supported by it.

Thanks

**Comment by samueleastdev** [comment]
I am also curious about this?

**Comment by m1ga** [comment]
https://github.com/arskinner/Appcelerator-CardIO/pull/13

**Comment by arskinner** [comment]
Fixed as of 2.0.4
