### ISSUE TITLE
New property for CVV setting ignored on iOS

### ISSUE THREAD

**Issue by bar-none** [arskinner/Appcelerator-CardIO#18]
Version 2.0.2 among other things moved the CVV option to a property.  But line 118 in the ComLikelysoftCardioModule.m class module found [here](https://github.com/arskinner/Appcelerator-CardIO/blob/master/iphone/Classes/ComLikelysoftCardioModule.m) references field cardIOLogo when it should set field collectCVV instead.  The net effect is collectCVV always keeps its initial setting, which is true.

**Comment by arskinner** [comment]
Good catch... just pushed the change and I'll post a new version

**Comment by bar-none** [comment]
Wow, that was FAST!

**Comment by bar-none** [comment]
Version 2.0.3 now correctly does not ask for the CVV when I use **cardio.setCollectCVV(false);** but the 'complete' event is not firing.  When I tap Done, the app crashes/exits to the iOS home screen.  When I use **true** it works, but requires the CVV entry.  I'm guessing perhaps it is not safe to reference info.cvv on lines 182 and 190 of that same class module, when collectCVV is false.

**Comment by arskinner** [comment]
Possibly, let me test

**Comment by arskinner** [comment]
This should be fixed in 2.0.4

**Comment by bar-none** [comment]
Confirmed it is fixed, at least for iOS.  Incidentally, your v2 also solves at two of the issues still listed as open.

**Comment by arskinner** [comment]
Thanks... looks like all the issues are resolved actually. For now!
