### ISSUE TITLE
Error compiling a project with the module

### ISSUE THREAD

**Issue by kilyan-ubg** [arskinner/Appcelerator-CardIO#6]
Hi !

I found your module on gitt.io, I'm trying to use it in a new project but the project build fails every time.

This is what I did:
  • I downloaded the module from github
  • Updated the titanium SDK version to 5.1.1
  • Added libCardIO.a to the CardIO folder

Building the module via Titanium works fine but when I add it to a project I get this error when building the project : 

`[ERROR] :  ** BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :   Ld build/Intermediates/card.io.build/Debug-iphonesimulator/card.io.build/Objects-normal/x86_64/card.io normal x86_64
[ERROR] :  (1 failure)
2015-12-11T08:53:24.385Z | TRACE  | titanium exited with exit code 1
2015-12-11T08:53:24.388Z | ERROR  | Error: ti run exited with error code 1
    at ChildProcess.<anonymous> (/Users/kilyansockalingum/.appcelerator/install/5.1.0/package/node_modules/appc-cli-titanium/plugins/run.js:92:66)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
2015-12-11T08:53:24.389Z | TRACE  | Sending exit signal to titanium process:  25356
`

Thanks

**Comment by pravin-mindstix** [comment]
Hi,
I have same problem, Any luck ?

**Comment by yozef** [comment]
I was able to successfully build the module (with tweaks to the manifest) & adding `libCardIO.a` to `/iphone/CardIO` folder.


However when using the module within the App on iOS, I get:
```
[ERROR] :  ** BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :  	Ld build/Intermediates/myapp.build/Debug-iphoneos/myapp.build/Objects-normal/arm64/myapp normal arm64
[ERROR] :  (1 failure)
```

It seems post Ti 5.2.0.GA the way the module is built has changed ([iOS Module post 5.2](http://docs.appcelerator.com/platform/latest/#!/guide/iOS_Module_Project-section-src-43288810_iOSModuleProject-ProjectStructure))

**Comment by arskinner** [comment]
I have updated the README to reference the new build command, which should be working
